name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  workflow_dispatch:

jobs:
  ci-validation:
    name: CI Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: pnpm setup
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: |
          pnpm i

      - name: Run CI checks
        # Note that we must use the run verb, as pnpm ci is reserved.
        run: |
          pnpm run ci
